name: Test Github Action

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: action/checkout@v3
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
